### ISSUE TITLE
[ISSUE] Unable to find extension method GameCenter_Leaderboard_Submit on class GameCenter

### ISSUE THREAD

**Issue by drewster99** [YoYoGames/GMEXT-GameCenter#4]
I'm seeing this when running on iOS after building with YYC, which I assume means it's not working:

>  Unable to find extension method GameCenter_Leaderboard_Submit on class GameCenter

IDE v2023.2.1.75
Runtime v2023.2.1.90

Looking at GameCenter.h and GameCenter.m ... Do these declarations need `(char *)` instead of `(NSString*)` types?

`-(double) GameCenter_Leaderboard_Submit: (NSString*) leaderboardID score: (double) score dcontext: (double) dcontext;`

**Comment by Bulletech** [comment]
Hello, this is still an issue, and unrelated to targeting YYC, any advice on a fix?

**Comment by jzavala-YYG** [comment]
This bug was fixed on Github.
SHA1 of the commit: d3c39e51600e791894ac4409e0a131b892c985d1

We will update the extension on marketplace soon as we can

**Comment by Bulletech** [comment]
Thanks for the update, maybe I’m missing something but I’m still getting the same issue from GitHub.
I have gone In GitHub: Code > Local > Download ZIP.
Then in GameMaker deleted the old extension then added the extension to my GameMaker project from source/GameCenter_gml/extensions/gamecenter/gamecenter.yy

Regards,
Bulletech

**Comment by HaikuJock** [comment]
`GameCenter_Leaderboard_Submit` takes a third argument, `context`, if you don't supply that argument you'll get the same error. The documentation for this extension needs updated too.

[Apple docs ](https://developer.apple.com/documentation/gamekit/gkleaderboard/3577544-submitscore?language=objc)
```
context
An integer value that your game uses.
```

**Comment by Bulletech** [comment]
> `GameCenter_Leaderboard_Submit` takes a third argument, `context`, if you don't supply that argument you'll get the same error. The documentation for this extension needs updated too.
> 
> [Apple docs ](https://developer.apple.com/documentation/gamekit/gkleaderboard/3577544-submitscore?language=objc)
> 
> ```
> context
> An integer value that your game uses.
> ```

Thank you @HaikuJock !

**Comment by YYBartT** [comment]
The `context` parameter was already listed under `GameCenter_Leaderboard_Submit`. Added the description above to clarify and updated the wiki with the changes.
